name: "🐛 Bug Report"
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line summary of the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce
      placeholder: |
        1. Start server with plugin version X
        2. Run command /...
        3. Observe error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
    validations:
      required: true
  - type: input
    id: plugin_version
    attributes:
      label: Plugin Version
      placeholder: "e.g. v1.2.10"
    validations:
      required: true
  - type: input
    id: server_version
    attributes:
      label: Server Version
      description: Output of /version
      placeholder: "e.g. Paper 1.21.4-123"
    validations:
      required: true
  - type: input
    id: java_version
    attributes:
      label: Java Version
      placeholder: "e.g. Java 21.0.2"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Stacktrace
      description: Relevant console output (use code block)
      render: shell
  - type: textarea
    id: extra
    attributes:
      label: Additional Context
      description: Screenshots, configs, other plugins installed, etc.
